### ISSUE TITLE
 404 Not Found (from disk cache)

### ISSUE THREAD

**Issue by damnsanga** [enymawse/stasharr#16]
Config Settings:
![image](https://github.com/user-attachments/assets/cd2f945b-fc1c-4757-8392-188b4c2d1f6d)

Webpage Dev Tools Output:
![image](https://github.com/user-attachments/assets/c249247b-683d-4df8-a8b5-a1d13a6c428c)
.
![image](https://github.com/user-attachments/assets/a794110a-efe1-456c-9b3b-c6d79d092dd3)
.
About Whisparr: Installed on a lxc and accessed via local LAN address.

**Comment by enymawse** [comment]
Thank you for bringing this up as I've noticed it before, however, this isn't related to the userscript. The manifest.json file is a stashdb.org asset that's not found when loading the page irrespective of the userscript being installed.
