### ISSUE TITLE
Feature: Add ability to batch add scenes that are NOT flagged as 'Already in Whisparr'

### ISSUE THREAD

**Issue by 2pnk1stnk** [enymawse/stasharr#19]
This would be a nice addition to an already great tool. This will significantly mitigate the issue where Whisparr has trouble grabbing scenes from Skyhook for performers with 100+ scenes.

**Comment by enymawse** [comment]
Love the feedback. How do you envision this being presented to the user? A button on the performers page as simple as "Add All Available Scenes"?

And so I understand the issue with Skyhook properly: Performers with 100+ scenes don't get added to Whisparr via monitoring or import lists?

**Comment by 2pnk1stnk** [comment]
_How do you envision this being presented to the user? A button on the performers page as simple as "Add All Available Scenes"?_

Yes. That sounds perfect. Clean, simple and to the point

...not sure about that in regards to import lists, but basically how it goes is, say you add a performer and they have a few to zero scenes populated, well if you want all their scenes you monitor them and then click refresh and scan. Well, what has been observed is that when a performer has 100+ scenes not all of their scenes get grabbed. That's about all I can tell you about it. As to why or which files it omits, I cannot speak on. It's my understanding that Skyhook is a black box. With this feature enabled, it will make help people gather any scenes Whisparr may have missed out on in an easier fashion.

**Comment by sampulsar** [comment]
@enymawse 

Sometime the issue is that the performers works is not complete, but the scene metadata is actually available. The "Add All Available Scenes" button would just click all of the buttons that can add a scene.

The WhisparrService.searchScene call can also detect any scenes that are present on StashDB but not on SkyHook. I think the button should change to red if this fails to return data. The call should only be done when the user is adding the scene.

This then provides additional feedback.

**Comment by enymawse** [comment]
If the script is going to bulk add missing scenes from a performer I think getting the full list of scenes that performer is in might be best done using the stashdb graphql endpoint then excluding those from the ones added (and if applicable ones on the exclusion list). Unless you (@sampulsar) know of a way to do that via the whisparr api without running into Skyhook issues?

**Comment by sampulsar** [comment]
I was thinking of just bulk adding those on the page. Skyhook may not always be 100% correct when looking at pereformers/work, as the scene may actually exist in skyhook.

The stashdb graphql endpoint you need to page every 100 items, and is more complex. You will then likely get more request about all item's but with a filter on date, studio, etc.

Go with the simple solution initially and just by page.

**Comment by enymawse** [comment]
Yeah that makes sense. One button to immediately add 100s of scenes is the nuclear option. I agree with you, simple solution, the button would add those scenes listed on the current page.
