### ISSUE TITLE
Feature: Ability to measure against Import List Exclusions

### ISSUE THREAD

**Issue by 2pnk1stnk** [enymawse/stasharr#23]
I believe this feature would round out this plugin:

If possible, essentially this would add an icon, so that we can distinguish between scenes that we have manually and purposely excluded vs. those that were never pulled from an initial Refresh & Scan

Currently I see scenes that I know I've manually excluded as having the pink icon

**Comment by sampulsar** [comment]
/api/v3/exclusions will return excluded list. I think it a string list and any containing a "-" will be a stashId. It also return the movies that are just integers from TMDB
