### ISSUE TITLE
Request: I have 2 different instances, soon to be 3 of Whisparr. V1, V2, and V3

### ISSUE THREAD

**Issue by MrMxyzptlk** [enymawse/stasharr#37]
Please add the ability to send to multiple Whisparr instances.

Thank you for your time!

**Comment by enymawse** [comment]
Whisparr V3 gets its metadata (and scene identification) from StashDB. V2 gets it from TPDB. Using Stasharr is specifically for use with StashDB (not TPDB) and thus purpose built for Whisparr V3 instances. Getting something like this to work with V2 would be an entirely separate undertaking.
I appreciate the community's involvement and thank you for your interest.

**Comment by MrMxyzptlk** [comment]
I understand; thank you for your reply.
