### ISSUE TITLE
Feature: Add Studio and Performer buttons

### ISSUE THREAD

**Issue by sampulsar** [enymawse/stasharr#5]
Pull request https://github.com/Whisparr/Whisparr/pull/274 will allow a studio or performers information to be returned by a stashID

You could do something to toggle on monitoring, or perform a search. Example of showing if a performer is monitored

    // Function to add the button when the card-header element is found
    function addButtonToPerfomerHeader() {
        const cardHeader = document.querySelector('.PerformerInfo .card-header');
        if (cardHeader && !document.querySelector('#whisparrButtonHeader')) {
            const triggerButton = createHeaderButton();
            cardHeader.appendChild(triggerButton);
            const performerID = window.location.href.split(`https://stashdb.org/performers/`)[1];
            handlePerformerLookup(triggerButton, performerID, true);
        }
    }

  function handlePerformerLookup(button, performerID, isHeader) {
        if (performerID) {
            const fullApiUrl = `${config.apiUrl}performer?stashId=${encodeURIComponent(performerID)}`;
            fetch(fullApiUrl, { method: 'GET', headers: createHeaders() })
                .then(response => response.json())
                .then(data => {
                    if (data?.length > 0) {
                        if (data[0].monitored) {
                            button.innerHTML = '<i class="fa-solid fa-check-circle">';
                            button.style.color = '#ffffffcc';
                            button.style.backgroundColor = '#4CAF50';;
                        } else {
                            button.innerHTML = '<i class="fa-solid fa-download">';
                            button.style.backgroundColor = '#e385ed';
                            button.style.color = '#ffffffcc';
                        }

                    }
                })
                .catch(error => {
                    console.error('API Call Error:', error);
                    showToast('Error checking scene in Whisparr.', false);
                });
        } else {
            console.log('No StashID in the URL.');
            showToast('No valid StashID found in the URL.', false);
        }
    }

**Comment by enymawse** [comment]
Completely redesigned the userscript. I'm going to put this in the backlog for sure. I like this idea for those that dont use the Import List for StashDB favorites.

**Comment by enymawse** [comment]
Working this in branch `feature/add-studio-monitoring-toggle`.

**Comment by sampulsar** [comment]
@enymawse 

When I initially used it I was going to put a place holder before it calls the api, so that it would say loading like on the buttons.

It was a rush job to give you a good head start on displaying this information. The code looks good.

**Comment by enymawse** [comment]
Being monitored or unmonitored must be predicated by the studio or performer existing in the users Whisparr instance otherwise when querying Whisparr, WhisparrService.handleStudioLookup wouldn't return anything. 

I haven't found a way to add a studio into Whisparr via the API, maybe I totally missed it but I don't think it's there.

**Comment by sampulsar** [comment]
Added it as a pull request https://github.com/Whisparr/Whisparr/pull/288
